name:                timezone-diagram
version:             0.1.0.0
github:              "davecturner/timezone-diagram"
license:             BSD3
author:              "David Turner"
maintainer:          "dave.c.turner@gmail.com"
copyright:           "2019 David Turner"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/davecturner/timezone-diagram#readme>

dependencies:
- base >= 4.7 && < 5
- cairo
- pango
- mtl

library:
  source-dirs: src

tests:
  timezone-diagram-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timezone-diagram
